dealii/candi

candi.sh

(unreadable on a shell with white background)

change warning color from yellow to purple

---

deal.II-toolchain/packages/numdiff.package

numdiff is not installed by default and strictly speaking not a
dependency of deal.II, but it is very convenient to be able to do
./candi.sh --packages="numdiff"
and have it installed automatically.

add numdiff package

---

deal.II-toolchain/packages/p4est.package

If zlib is installed as part of candi (or manually by setting ZLIB_*),
pass this info to p4est. It turns out p4est won't work (at least in
debug mode) without having access to zlib. So enforce that too.

Fix p4est without zlib

---

candi.sh
deal.II-toolchain/platforms/supported/macosx.platform

- add detection for OSX and shows a temporary platform info
- remove nano-second timing computation because it is broken on mac
note: not all packages are working correctly but some do.

preliminary mac osx support

---

deal.II-toolchain/packages/dealii-prepare.package

Related to #29. The same cluster uses bash version 3.2 (released in 2007, the cluster was build last year, but runs Suse Linux Enterprise Server 11). The function to transform upper to lower case that is used by candi was introduced in bash 4.0. According to a google search `tr` is hopefully more standard conform, but again, I have little experience, so I am happy about suggestions how to improve.

Use tr instead of bash specific command

---

deal.II-toolchain/packages/dealii.package

PARPACK support is disabled inside deal.II by default, but our version
is recent enough.

enable PARPACK support

---

deal.II-toolchain/packages/dealii.package

I used candi to install deal.II on a somewhat particular cluster (CRAY XC40), and for that I needed to set some user options. I created a minimal platform file with only the packages I needed, but its specific options were overwritten by the options set in dealii.package, because user options are interpreted first. This PR fixed my problem, but I have to admit I do not know if there are cases where it breaks other things (are there options that need to be specified first, e.g. compilers? Are some of the listed options necessary, even if the user tries to explicitly disable them?). In my specific case I want to force the bundled boost (the external does not compile cleanly), and I do not want LAPACK and UMFPACK, because I do not need them for my setup, and hard disk space and number of …

Follow user options

---

candi.sh
deal.II-toolchain/platforms/contributed/cray.platform

This supersedes #31. We should wait with merging until the discussion on the mailing list about PETSc and MUMPS support has come to a conclusion, but otherwise this should be ready. It now automatically detects a Cray operating system.

Add cray support

---

deal.II-toolchain/packages/parmetis.package

To compile parmetis on a system that does not use `mpicc` as MPI compiler we need to patch its Makefile, because somebody in the parmetis project decided `mpicc` is the only *true* command, and always set `-DMPI_C_COMPILER=mpicc` during the call to cmake :smile:. I also patch the c++ compiler, because parmetis sets this for cmake as well, although it does not seem to use it (but since cmake checks for its existence I get errors if I do not patch it).
There is one complication here: If there are systems that set `$CC` to a compiler that is not able to compile MPI libraries then so far that did work (because Parmetis implicitly used mpicc anyway). This might now break, but I do not quite know what to do about it. I see no other way to allow specifying a different compiler than mpicc.
This …

Allow other compiler wrappers than mpicc

---

deal.II-toolchain/packages/p4est.package
deal.II-toolchain/platforms/contributed/cray.platform

One more follow-up resulting from #32. candi uses FF as Fortran 77 compiler, while GNU autoconf (as used for p4est) looks for F77. If now FF is set to a correct user-provided compiler, but F77 is empty (then replaced by mpif77) or set to a different value p4est tries to use F77 and might fail. Instead we can explicitly set F77 to the value of FF during configuring p4est. No other included package seems to use autoconf with enabled fortran check so this should be a p4est specific fix.
This change simplifies the configuration for systems with non-default compilers (as can be seen in the cray platform file).

Use FF as Fortran77 compiler in p4est

---

deal.II-toolchain/packages/hdf5.package

Updated minor version to v1.10.1 from v1.10.0-patch1.
Download and build was successful on my system.

hdf5: updated minor version to v1.10.1 from v1.10.0-patch1

---

deal.II-toolchain/packages/petsc.package

If PETSC_DIR is already set in the environment, configuration of PETSC fails,
so just unset it before.

unset PETSC_DIR

---

README.md
candi.cfg
deal.II-toolchain/packages/git.package

I had to guide a user through the manual installation of git on a cluster to allow them to use candi. I think we can make this easier by providing a git package. Also I think the system dependency packages that are already available should be mentioned in candi.cfg. This way users immediately see what can be additionally installed.

Add git package

---

candi.sh
deal.II-toolchain/packages/arpack-ng.package

Without this patch arpack-ng was not correctly detected for package SKIP. Works now, also for all other packages.

Successful build detection

---

deal.II-toolchain/platforms/supported/linux_cluster.platform

This removes forcing individual packages in the generic `linux_cluster.platform` file.
Individual packages are currently configured in the central `candi.cfg` configuration file.
Resolves the reported issue from here:
https://groups.google.com/forum/#!topic/dealii/QNTdIDgxv1c

updates linux_cluster_platform

---

candi.sh
deal.II-toolchain/packages/opencascade.package
deal.II-toolchain/patches/oce-xlocale.patch

This PR includes:
- a new function `package_specific_patch` to be applied after `package_unpack`
- a patch for opencascade oce v0.18.1 for a missing `xlocale.h` with glibc v2.26
- updates package opencascade to v0.18.2
It resolves #56 .
Tested with glibc 2.25 for oce v0.18.1 and v0.18.2 with the applied patch.
Since I do not have glibc 2.26 I cannot test this.

opencascade patch glibc xlocale.h missing and v0.18.2

---

deal.II-toolchain/packages/boost.package

boost fails to compile with "pyconfig.h: No such file or directory"
because of a broken include path setting inside boost. Instead of
fixing/updating boost (which we can't do because newer boost version are
also not working correctly), just disable the python support inside
boost. We are not using that anyways.

remove python from boost config

---

deal.II-toolchain/packages/dealii-prepare.package
deal.II-toolchain/packages/dealii.package

Check if cmake 3.10 (or above) used with deal.II v8.5.1 and outputs useful hints to resolve the find mpi problem.
candi recommends that the package cmake from the config file is switched on, if so everything works well again on F26 (ships currently cmake 3.10.1)

check if cmake 3.10 used with deal.II v8.5.1 

---

deal.II-toolchain/platforms/supported/fedora27.platform

the changes are tested today. even cmake 3.9 / 3.11 together with dealii v8.5.1 works as expected

adds fedora 27 as supported platform

---

deal.II-toolchain/packages/boost.package

adolc and possibly other tools want BOOST_DIR instead of BOOST_ROOT, so
provide it.

also export BOOST_DIR

---

candi.sh

In `python` 3 we need these brackets and they are compatible with `python` 2 as well.

Fix calling python print

---

deal.II-toolchain/packages/cmake.package

This PR resolves the cmake issue (needing at most v3.9 or less for deal.II v8.5.1) on macOS by downloading, compiling and installing cmake instead of just downloading the binary tarball.
Further optimisation is to check, if the platform is linux and then download only the tarball and additionally, if cmake needs to be compiled, check if cmake or autotools with bootstrap as buildchain is needed.
This PR is tested to be working on the latest macOS and fedora 27.

cmake package: now compiles and installs again v3.9

---

deal.II-toolchain/packages/cmake.package
deal.II-toolchain/packages/dealii-prepare.package
deal.II-toolchain/packages/dealii.package

- automatically uses tarball install or cmake/autotools depending on the platform and the availbility of cmake
- updates to v3.11.2 from 3.9.6

cmake update and tarball

---

deal.II-toolchain/packages/parmetis.package

Since commit b6e293838e286b44e2031e5734d6579dd4220fbe it seems that the MacOS build for at least superlu_dist and trilinos is broken. This PR resolves that in a way, that only on linux type OS platforms the patch for parmetis 4.0.3 will be applied. I'm still working on a solution for mac os including the patch, but this will be done in a future PR.

Bugfix parmetis macos

---

deal.II-toolchain/packages/trilinos.package
deal.II-toolchain/platforms/supported/centos7.platform
deal.II-toolchain/platforms/supported/rhel7.platform

This PR resolves the current issue on centos 7 that parmetis is not detected in its correct version.
I've run a test on a centos 7 machine, now the default configuration compiles correctly and step-32 and step-42 (trilinos step tutorials) runs fine.

centos 7: bug: force to have parmetis 4.0.3 installed

---

deal.II-toolchain/platforms/supported/debian9.platform

This is the same workaround as in issue #85.

debian 9: bug: force to have parmetis 4.0.3 installed

---

deal.II-toolchain/platforms/supported/debian9.platform

On Debian 9, `libblas3gf` and `liblapack3gf` are replaced by `libblas3` and `liblapack3`, respectively. These were previous [transitional](https://packages.debian.org/jessie/libblas3gf) [packages](https://packages.debian.org/jessie/liblapack3gf) in the previous Debian 8 release.
Also replace "ubuntu's" with "debian's" in the description.

Update apt-get instructions for debian9.platform

---

deal.II-toolchain/packages/p4est.package
deal.II-toolchain/packages/zlib.package

If only `ZLIB_DIR` is set, an p4est MPI C error might occur, since zlib is not correctly embedded to the p4est configuration. This PR resolves this issue.
Note that this can currently not happen for the zlib.package provided by candi - but anyhow - for different installations this is a problem.

p4est: corrects zlib detection for user-installed zlib

---

deal.II-toolchain/packages/petsc.package

Turns out we already install scalapack as part of PETSc. By exporting this path, deal.II will be able to find it.

add export for SCALAPACK

---

candi.cfg

simple test run on fedora 28 with default compiler works fine. I think this should be safe to merge.

switch deal.II v9.0.0 -> v9.0.1

---

candi.cfg
candi.sh
deal.II-toolchain/packages/dealii.package

This PR is an enhancement to candi to allow for cherry-picks of development commits to a stable release.
The reason is, that a more or less long time undergoes between two stable releases within a package and sometimes there is the need (for a candi-user or from our developer side) to select a very little number of (development) commits added to a stable release without using the complete unstable development version.
This PR includes an example for a bugfix of a deal.II class (disabled by default), but it can be used for other packages which we check out with git.
For future use, maybe problems as in PR #92 can be easily resolved with that within candi.
I barely checked that this PR does not break anything in candi, i.e. initial build experience for deal.II v9.0.0 for fedora 28. Further …

git cherry-pick enhancement

---

deal.II-toolchain/platforms/supported/opensuse15.platform

- switch to mpich (fewer runtime warnings)
- install ld gold (avoids slow linking)

opensuse fixes

---

deal.II-toolchain/packages/cmake.package

otherwise $PATH will be expanded in the config file. We do this in all other packages already.

fix path directive in cmake package

---

candi.cfg
deal.II-toolchain/packages/dealii.package
deal.II-toolchain/packages/petsc.package

Introduce a new settings to allow native optimizations. This currently
affects PETSc and deal.II (basically setting march=native).

add optimization option

---

candi.cfg
deal.II-toolchain/packages/dealii.package
deal.II-toolchain/packages/petsc.package

Introduce a new settings to allow native optimizations. This currently
affects PETSc and deal.II (basically setting march=native).

take over #111 to dealii-9.0

---

deal.II-toolchain/packages/hdf5.package

Required to link with a newer version of MPI:
```
/home/heister/shared-
dealii/dealii-v9.1.1/tmp/unpack/hdf5-1.10.1/testpar/t_cache.c:1222:27:
error: call to ‘MPI_Address’ declared with attribute error: MPI_Address
was removed in MPI-3.0.  Use MPI_Get_address instead.
```
This should go into 9.1 as well.

update hdf5 to 1.10.5

---

candi.sh
deal.II-toolchain/packages/trilinos.package

- allow alternative checksums to be specified
- add a second checksum for trilinos as the original file changed

allow checksum alternatives to fix trilinos download

---

.github/workflows/main.yml

Use github actions for some simple build tests:
- ubuntu 18: MPI, gcc, p4est and deal.II
- OSX minimal: clang, serial, just deal.II
- OSX parallel: gcc9, MPI, p4est and deal.II
These builds happen in parallel and take close to 2hrs, but I think this is acceptable for the development. They will automatically run on every pull request and push.
(currently based on #131 to compile on MacOS)

simple continuous integration using github actions

---

deal.II-toolchain/platforms/supported/ubuntu16.platform
deal.II-toolchain/platforms/supported/ubuntu18.platform
deal.II-toolchain/platforms/supported/ubuntu19.platform
deal.II-toolchain/platforms/supported/ubuntu20.platform

Docker images for various ubuntu version are very lightweight and don't provide some basic packages. I was installing candi in a docker environment and realized the script needs `python` and Trilinos installation needs the `bc` command. These packages are available on almost all desktop installations of ubuntu, but I think we should remind the user to install them on docker images.

bc and python must be available on ubuntu

---

deal.II-toolchain/platforms/supported/centos7.platform

By default the cmake package from centos is too old to build Trilionos (and possibly dealii as well):
```
$ cmake --version
cmake version 2.8.12.2
```
There is a cmake3 package, but it installs as cmake3, an alternative to this PR might be to install `cmake3` as a prerequisite and somehow tell the build process to use `cmake3` instead of `cmake`
```
$ cmake3 --version
cmake3 version 3.17.3
```
This change tells candii to fetch and build cmake from source instead of worrying about what version the system has.

Addresses issue #154 CentOS cmake is too old

---

.github/workflows/main.yml

- force cmake 3.18 as 9.2 does not support 3.19 (default in the VM)
- change the minimal build to use MPI as well (without it, blas is not
found for some reason). There is no good reason to test candi builds
without MPI.

CI: fix OSX tester

---

candi.cfg
candi.sh
deal.II-toolchain/packages/petsc.package
deal.II-toolchain/packages/slepc.package

If "python" does not exist in the environment, we set PYTHONVER to the
empty string, which makes configuration fail. Fix this.

handle python3 correctly

---

deal.II-toolchain/packages/trilinos.package

The choice to disable TPetra when using MKL lead to several downstream
Trilinos configuration errors. Instead, just disable the two
instantiations that are missing in MKL. Tested to work correctly with
Intel 19.0.5 and MKL.

fix trilinos tpetra when using intel MKL

---

deal.II-toolchain/packages/arpack-ng.package

This updates to the latest arpack-ng version since 3.6.2 failed on my system, compare #168.

Update to latest arpack version 3.8.0

---

candi.cfg
deal.II-toolchain/packages/dealii.package

In my experience, building the dealii tutorials is quite time consuming and if one specific is needed it can be build on demand in a local workdir. So this option allows a flag whether to enable or disable the build of the dealii tutorials.
Personally, I would also be interested in how to set up the continuous integration for testing this (i.e. how to test both cases true|false).

Option whether to build dealii examples

---

deal.II-toolchain/packages/cmake.package

This updates the bundled cmake installation to version 3.16.3. At the moment, the Ubuntu 20.04 CI tests the cmake package.

Update cmake to version 3.16.3

---

candi.cfg
deal.II-toolchain/packages/dealii.package

This adds an option RUN_DEAL_II_TESTS={ON|OFF} to the configureation file to run the dealii tests (make test) after installation.

Add option to run tests after installation

---

deal.II-toolchain/packages/dealii.package

As described in the comment, it is not ideal to set CXX/CC.

disable CXX/CC for deal.II itself

---

candi.cfg

it makes sense to test the latest deal.II master version on the candi
master branch (in contrast to the 9.x branches)

on the master branch always use dev deal.II version

---

.gitignore

I was annoyed, that my .vscode dir was always listed in git status, so I copied some lines from the gitignore file of dealii/dealii. Please tell me if some files are too much. @koecher were the candi/tmp dirs (I commented them this way) for your personal folder structure (originally?)

Extend gitignore file

---

candi.cfg
deal.II-toolchain/packages/dealii.package

Setting the compiler wrapper in CMake instead of in CC and CXX is
recommended, but only works for recent CMake versions (one configuration
I tested requires CMake 3.20 for the intel compiler).
With 9.3.1 deal.II supports setting CXX=mpicxx again, so only do the
above when a setting in candi.cfg is specified.
Works around #202
and fixes feature introduced in #159

only set MPI_CXX_COMPILER if requested

---

.github/workflows/main.yml
candi.sh

I assume you use a manually specified install dir? However, for consistency I would like to suggest changing the default install path to either deal.II-candi or dealii-candi. Personally I like dealii-candi, as no dots are in this name.

Update default install prefix

---

deal.II-toolchain/packages/adolc.package
deal.II-toolchain/packages/dealii.package

Update the checksums for ADOL-C and enable tarball download by default. Test is currently running via github actions in my fork, see https://github.com/gfcas/candi/actions/runs/982865293

Update package adolc

---

deal.II-toolchain/packages/cmake.package

- this updates the version to 3.20.5 for (linux) tarball install and source install.
- adds switch `CANDI_CMAKE_LOAD_TARBALL`
- in issue #202 it is reported, that using v3.20 resolves a compiler issue
- tarball and src based install was successfully tested on centos7
Since the tarball source file naming scheme has changed from v3.16 to v3.20, the checksums for older versions are removed.

cmake 3.20.5

---

deal.II-toolchain/packages/arpack-ng.package
deal.II-toolchain/packages/dealii.package

This updates the arpack package file. Up to minor indention fixes afterwards the tests on Ubuntu were OK (https://github.com/gfcas/candi/actions/runs/986593992). However, testing it with the OSX-clang setup (see main.yml) an error is throw during the arpack configuration:
```
The Fortran compiler
"/usr/local/bin/mpif90"
is not able to compile a simple test program.
```

Update arpackg-ng package

---

candi.cfg
deal.II-toolchain/packages/trilinos.package

Trilinos complex support is not needed in deal.II, unless complex Tpetra
vectors are used (unlikely). Enabling it requires large amounts of RAM
(we are talking 10GB per process). Instead, introduce an option that
defaults to OFF.
Also do not specify Tpetra_INST_* see https://github.com/dealii/dealii/pull/8945
fixes #219

Trilinos: add complex option

---

deal.II-toolchain/packages/dealii.package
deal.II-toolchain/packages/sundials.package

Update of the SUNDIALS package file:
- Enable switch between tarball(default) and git download
- The source webpage for tarball download was deprecated
- The CONFOPT ``MPI_ENABLE`` was replaced by ``ENABLE_MPI`` (Unfortunately I dont know with which version this change is beginning, however, a deprecation warning is given on the terminal)
- Update to the latest stable release 5.7.0
- CI for sundials+dealii see https://github.com/gfcas/candi/actions/runs/1001803067

Update sundials package

---

candi.sh

default on OSX is zsh instead of bash and our enable.sh uses a bash
internal. This should work for bash and zsh.

fix enable.sh for zsh

---

deal.II-toolchain/packages/trilinos.package

I have no idea what this flag is good for and it fails for me on M1 OSX
with this, because there is no gfortran library.

trilinos: remove lgfortran flag

---

.github/workflows/main.yml

According to a hint of @koecher this is a bugfix for the broken gfortran symlink in GitHub Actions macos runners, see actions/virtual-environments/#2616.
Also we could update the gcc compilers of the macos-gcc job to version 11, which is the default, as I understood correctely?

Reinstall gcc compilers in macos ci jobs

---

deal.II-toolchain/packages/ginkgo.package

Ginkgo 1.4.0 is out so we can go from develop to the latest stable version. Previously it was only with develop possible to build the dealii+ginkgo interface correctly.

Ginkgo 1.4.0

---

candi.sh
deal.II-toolchain/platforms/supported/almalinux8.platform

CentOS 8 will have its end of life by the end of 2021. One can switch to AlmaLinux 8 as a replacement.

Adds platform AlmaLinux as replacement for CentOS 8

---

candi.cfg

As new version of dealii are release this comment would have to be adapted every time. Now it is independent.

Version independent comment

---

candi.sh

One can set the CMAKE_GENERATOR to set the default generator when cmake
is executed (I have set it to Ninja). This of course confuses candi, as
no makefiles will be generated.

unset CMAKE_GENERATOR

---

deal.II-toolchain/packages/opencascade.package
deal.II-toolchain/patches/oce-isfinite.patch

On M1 opencascade fails to compile, fix by adding a patch.
part of #196

opencascade: fix isfinite error

---

deal.II-toolchain/packages/adolc.package

These are the most sane set of options for ADOL-C that I know of. They allow us to make sure that the user can rely on the deal.II AD drivers to catch errors (`traceless_refcounting`). They also help permit the most natural coding style in terms of variable initialisation (`stdczero`) and allow traced/taped numbers to be used most robustly in functions with complex branch conditions (`advanced-branching`).

ADOL-C: Add default options that are most useful/defensive for users

---

deal.II-toolchain/packages/dealii.package

We found out that -O3 makes a measurable difference in matrix-free
performance for recent gcc versions. Enable this when the user requests
native optimizations.

native optimizations: enable -O3

---

deal.II-toolchain/packages/p4est.package
deal.II-toolchain/packages/trilinos.package

I wasn't sure if there was any reason why native optimizations wasn't turned on for anything else then deal.ii and pestc, so I tired it with trilinos, p4est and openblas. It seems to work for the first two, but I had issues setting it correctly for openblas. 
If there is any reason why this is not safe to do for these two packages, please let me know.

Add arch native flags to p4est and trilinos if native optimazations is on

---

deal.II-toolchain/packages/cmake.package

Same as
https://github.com/IBAMR/autoibamr/pull/79
but for candi.
autoibamr is like candi but for ibamr instead of deal.II - candi works well enough that I just copied and pasted it and added and removed dependencies. Hence bug reports for autoibamr sometimes apply here too.

Fix path to installed CMake files.

---

deal.II-toolchain/packages/petsc.package

fixes #306
I tried various combinations of single/double quotes and
reglob-protecting ${CONFOPTS} when passing to ./configure but none of
the options worked (PETSc either only picks up -O3 or fails to configure
with '-O3).

fix PETSc with optimization flags

---

deal.II-toolchain/packages/trilinos.package

- Trilinos 13.2.0
- Enable explicit instantiations #231
This fixes compilation on Ubuntu 22.04

update Trilinos to 13.2

---

deal.II-toolchain/packages/parmetis.package
deal.II-toolchain/patches/parmetis-4.0.3-64bit.patch

- When "USE_64_BIT_INDICES=ON" and install both ParMETIS & PETSc, The installation will be stopped with an error as shown below from the PETSc:
```
==============
Configuring PETSc to compile on your system                            
==============
==============
UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
==============
Metis specified is incompatible!
--with-64-bit-indices option requires a metis build with IDXTYPEWIDTH=64.
Suggest using --download-metis for a compatible metis
```
- After checking, it is the Line33 & Line 43 of "*/parmetis-4.0.3/metis/include/metis.h" that still keep
```
#define IDXTYPEWIDTH 32
```
& 
```
#define REALTYPEWIDTH 32
```
- Add an "if" block in the "parmetis.package". 
- If "USE_64_BIT_INDICES=ON", add extra pieces of codes in …

fix bug on metis installation when USE_64_BIT_INDICES=ON

---

deal.II-toolchain/packages/openblas.package

- When installing deal.ii with OpenBLAS, the installation will be stopped with an error as shown below from deal.ii:
```
[ 75%] Linking CXX executable ../bin/step-78.release
/usr/bin/ld: /lib/x86_64-linux-gnu/libblas.so.3: undefined reference to `gotoblas'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/step-9.release.dir/build.make:258: bin/step-9.release] Error 1
make[1]: *** [CMakeFiles/Makefile2:3939: examples/CMakeFiles/step-9.release.dir/all] Error 2
```
- According to OpenBLAS PR#3282 (https://github.com/xianyi/OpenBLAS/issues/3282), building OpenBLAS with 'DYNAMIC_ARCH=1' will fix the issue.
- Tested the modified candi on Ubuntu desktop.

fix issue on undefined reference to gotoblas

---

candi.sh
deal.II-toolchain/packages/petsc.package

Same as https://github.com/IBAMR/autoibamr/pull/120 but for candi. If a user has `PETSC_ARCH` set (i.e., by some system-wide PETSc install) then we want to unset it. Presently we only unset `PETSC_DIR`.
I didn't verify that this bug exists with candi too but I'm pretty sure it does since we run
```cmake
set(PETSC_DIR "" CACHE PATH "An optional hint to a PETSc directory")
set(PETSC_ARCH "" CACHE STRING "An optional hint to a PETSc arch")
set_if_empty(PETSC_DIR "$ENV{PETSC_DIR}")
set_if_empty(PETSC_ARCH "$ENV{PETSC_ARCH}")
```
in `FindPETSc.cmake` - i.e., we will, in this circumstance, set `PETSC_ARCH` to an invalid value.

Correctly unset PETSc environment variables.

---

deal.II-toolchain/packages/trilinos.package

explicitly enable NOX (even though it is active by default)
fixes #351

enable Trilinos NOX

---

Jenkinsfile

paths between 20.04 and 22.04 were being reused and causing compile errors

[CI] fix rebuilding on Jenkins

---

deal.II-toolchain/packages/petsc.package

fix PETSc download URL

---

deal.II-toolchain/packages/trilinos.package

In reference to https://github.com/trilinos/Trilinos/issues/12750.
See also: https://www.docs.trilinos.org/files/TrilinosBuildReference.html#enabling-float-and-complex-scalar-types
I moved the `ENABLE_FLOAT` option to the full configuration of Trilinos, as opposed to just for Teuchos. Is there a reason you only enabled it for Teuchos?

Update Trilinos configuration for complex & float.

---

deal.II-toolchain/packages/trilinos.package

A known bug in Kokkos causes candi to crash during the Trilinos compilation with `error: no member named 'sort_option' in 'SPADDHandle'`. This bug was fixed in Kokkos 4.5.1, which is now bundled with Trilinos [16.1.0](https://github.com/trilinos/Trilinos/releases/tag/trilinos-release-16-1-0). See Trilinos issue [#13570](https://github.com/trilinos/Trilinos/issues/13570).
Updating the Trilinos version and checksum from 16.0.0 to 16.1.0 in `deal.II-toolchain/packages/trilinos.package` fixes the issue. Candi now compiles Trilinos without crashing.
Tested on Apple M1 (arm64-apple-darwin24.4.0) with macOS 15.4.1 using mpicc (Apple clang version 17.0.0)

Use Trilinos 16.1.0 to fix Kokkos compilation error

---

candi.cfg

It looks like Trilinos 16 requires pnetcdf but we only have netcdf, so it doesn't work.

Trilinos: disable SEACAS by default

---

.github/workflows/main.yml
candi.cfg

- use CMAKE_MPI_COMPILER=ON by default
- OSX GA runner: remove arm64+GCC
- use gcc@13 for ARM

use CMAKE_MPI_COMPILER by default
