deal.II-toolchain/packages/trilinos.package
=> Set new repository (github.com) source for trilinos; updates to v12.10.1

deal.II-toolchain/packages/superlu_dist.package, deal.II-toolchain/packages/trilinos.package
Current super LU (dist) version. Now it is able to use cmake and build-in support for shared lib. Minor updates to Trilinos to get everything to work.
=> Superlu dist v5.1.2

candi.cfg
=> switch to 8.5.0

candi.cfg, deal.II-toolchain/packages/arpack-ng.package
=> add arpack

deal.II-toolchain/packages/opencascade.package
=> update opencascade to 0.18.1 and use tarball

README.md
I updated the README.md with some useful links, in particular the one to the complete list of available packages.
=> Add some links and update package list

candi.sh
Hi Uwe,
thanks a lot for teaching me on how to work with remote repositories and how to generate pull-requests!
As you can see, I seem to have the hang of it.
Lukas
=> Fixed strange grammatical flow

deal.II-toolchain/packages/git.package, deal.II-toolchain/packages/numdiff.package
instead of writing the current PATH, write "$PATH" by escaping it.
=> fix PATH in configuration

candi.cfg, deal.II-toolchain/packages/astyle.package
Not strictly speaking a dependency of deal.II but I am getting tired of
installing it manually.
=> add astyle

candi.sh, deal.II-toolchain/platforms/supported/highsierra.platform
adds MacOS 10.13 HighSierra as supported platform. Tested and working.
=> adds MacOS 10.13 HighSierra as supported platform

README.md
- updates the documentation README.md for Windows 10 instructions
- minor update such as removing export of mpi compilers and supported platforms
=> update README.md for WSL Win 10 1709 and other minor changes

deal.II-toolchain/packages/petsc.package
see comment for a description. This got reported by a user with OSX high sierra.
=> configure PETSc using python2

candi.cfg, deal.II-toolchain/packages/assimp.package
optional dependency for deal.II 9.0
=> add assimp v3.3.1

deal.II-toolchain/platforms/supported/ubuntu18.platform
Adds platform file for ubuntu 18 LTS, released April 2018.
=> add ubuntu 18 LTS

candi.cfg
Relates to dealii/dealii#6156.
=> Bump default deal.II version

deal.II-toolchain/packages/cmake.package
cmake sets the incorrect install path if you use "once:cmake"
=> fix cmake path

candi.sh, deal.II-toolchain/platforms/supported/opensuse15.platform
This is somewhat bare bones so far and not every package is working, but this is much better than no support. :-)
=> support opensuse 15

candi.cfg, deal.II-toolchain/packages/openblas.package, deal.II-toolchain/packages/petsc.package
=> add openblas

deal.II-toolchain/packages/trilinos.package, deal.II-toolchain/platforms/supported/opensuse15.platform
- missing python2
- missing g++ (devel_C_C++ only installs cpp)
- add documentation for mpi wrappers
- trilinos also wants libmetis to work (not sure why)
closes #100
=> opensuse fixes

deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/petsc.package
make the change in #111 also on master
=> fix bash multiline

deal.II-toolchain/platforms/supported/elcapitan.platform, deal.II-toolchain/platforms/supported/highsierra.platform
these options have disappeared from homebrew...
=> OSX  doc update

candi.sh, deal.II-toolchain/platforms/supported/catalina.platform, deal.II-toolchain/platforms/supported/mojave.platform
- add platform detection
- update homebrew instructions
- fixes #130
=> OSX 10.14 and 10.15 support

.github/workflows/main.yml
maybe this tells us something about #133
=> add github action to include petsc on OSX

.github/workflows/main.yml
this might fix occasional reference is not a tree errors.
=> CI: switch to checkout v2

candi.sh, deal.II-toolchain/packages/adolc.package, deal.II-toolchain/packages/petsc.package, deal.II-toolchain/packages/slepc.package, deal.II-toolchain/platforms/supported/arch.platform, deal.II-toolchain/platforms/supported/ubuntu20.platform
take over #137 #136 #140 to the new 9.2 branch
=> [9.2] take over recently merged PRs

candi.sh, deal.II-toolchain/platforms/supported/centos7.platform, deal.II-toolchain/platforms/supported/debian10.platform, deal.II-toolchain/platforms/supported/debian9.platform, deal.II-toolchain/platforms/supported/rhel7.platform
Adding support for the current verion of debian.
I tested candi on debian 10 with this configuration.
=> Adding Debian 10 support

deal.II-toolchain/platforms/supported/centos7.platform
https://github.com/dealii/candi/issues/155
=> Addresses issue #155 old CentOS compilers

deal.II-toolchain/platforms/supported/centos7.platform
=> take over #154 and #157 (centos cmake) to master branch

deal.II-toolchain/packages/muparser.package
This is not used by default, but helpful for me to use in external projects.
=> add muparser as separate package

README.md, candi.sh
Resubmit of skip prompts option to the master branch.
=> Add option to skip prompts

candi.cfg, candi.sh, deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/petsc.package, deal.II-toolchain/platforms/deprecated/ubuntu14.platform
This patch switch the visible options in the candi.cfg file to ON|OFF, see #174.
=> Unification ON|OFF

candi.cfg, candi.sh
See #181. Updated after our discussion (@koecher)
=> Add instant clean up option

deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/superlu_dist.package, deal.II-toolchain/packages/trilinos.package
Beside cleanup and indention this PR integrates the suggested chages from #185. However, needs to be tested.
=> Update package trilinos

README.md, candi.sh, deal.II-toolchain/packages/astyle.package, deal.II-toolchain/packages/boost.package, deal.II-toolchain/packages/openblas.package, deal.II-toolchain/packages/p4est.package, deal.II-toolchain/packages/parmetis.package
The option --jobs replacing --PROCS would be more similar to the 'make' style.
=> Replace option --PROCS by --jobs

candi.cfg, deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/symengine.package, deal.II-toolchain/platforms/supported/ubuntu20.platform
This adds the 0.7.0 version of symengine. (Updated version of #118).
=> Add package symengine

.gitignore
=> Remove candi dirs from .gitignore

candi.sh, deal.II-toolchain/packages/dealii-prepare.package
=> Update user interaction

candi.sh
- Remove duplicated code
- Add a comment
- Unset the PREFIX variable as it is no longer used
=> Update prefix option handling

deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/opencascade.package
Update opencascade package file. Tests running.
=> Update package opencascade

deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/p4est.package
Indention etc. Should be without any code change.
=> Update package p4est

deal.II-toolchain/packages/adolc.package, deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/gmsh.package, deal.II-toolchain/packages/opencascade.package, deal.II-toolchain/packages/symengine.package
@koecher this is a minor update of the CANDI_${PACKAGE}_LOAD_TARBALL option related to the comments in #221. Additionally some missing ${PACKAGE}_DIR were added in dealii.package.
=> Minor consistency update

candi.sh
Replacement for #228, now against master.
=> Say what option it is that isn't recognized.

candi.sh
Write out some variable names in ``guess_platform()``
Note: This PR must be rebased after #236.
=> Rename some variables in guess_platform()

candi.sh, deal.II-toolchain/platforms/supported/macos.platform, deal.II-toolchain/platforms/supported/macos_bigsur.platform
- detects macos bigsur 11.5.1 (current update)
- updates install instructions for macos bigsur
- detects version independent macos
=> macos update (bigsur update 11.5.1)

deal.II-toolchain/packages/ginkgo.package
Add comments on two ginkgo configuration options, which inrease the performance of certain algorithms, see also https://github.com/ginkgo-project/ginkgo/issues/873.
=> Add comment on advanced ginkgo options

deal.II-toolchain/packages/p4est.package
Update ``p4est.package`` according to the current state in https://github.com/dealii/dealii/blob/master/doc/external-libs/p4est-setup.sh
=> Update p4est.package according to dealii

deal.II-toolchain/packages/dealii.package, deal.II-toolchain/packages/petsc.package, deal.II-toolchain/packages/slepc.package
@tjhei Thanks for the update of petsc and slepc in #275. I had some minor clean ups for this patch from previous developments.
=> Clean up PETSc and SLEPc

.github/workflows/main.yml
As in dealii/dealii this prevents of multiple jobs for the same pull request. Only the latest push on the PR is tested on the github runners. In addition an indentation was performed.
=> Concurrency

candi.sh
Put the PR to the master branch.
=> Fixed `BUILDDIR` spelling error.

deal.II-toolchain/packages/adolc.package, deal.II-toolchain/packages/p4est.package, deal.II-toolchain/packages/trilinos.package
resolves #292 by taking over commits from dealii-9.3 branch to the master branch.
=> Takeover 267 289

.github/workflows/main.yml
According to dependabot from dealii/dealii.
=> Bump github actions/checkout@v3

deal.II-toolchain/packages/cmake.package
=> Fix path to installed CMake files.

deal.II-toolchain/packages/trilinos.package
- netcdf support in trilinos needs some help to find correct paths
- SEACAS depends on netcdf
=> fix SEACAS support

deal.II-toolchain/packages/trilinos.package
=> disable x11

deal.II-toolchain/packages/trilinos.package
While building with the latest version of Trilinos with two ranks, the following errors occur: 
> [ 76%] Built target stratimikosaztecoo
Consolidate compiler generated dependencies of target stratimikosamesos2
[ 76%] Built target stratimikosamesos2
Consolidate compiler generated dependencies of target stratimikosbelos
[ 77%] Built target stratimikosbelos
Consolidate compiler generated dependencies of target stratimikos
[ 77%] Built target stratimikos
Consolidate compiler generated dependencies of target teko
[ 77%] Linking CXX shared library libteko.so
/usr/bin/ld: CMakeFiles/teko.dir/NS/Teko_InvModALStrategy.cpp.o: in function `Stratimikos::LinearSolverBuilder<double>::initializeDefaults()':
/home/testinf/dealii-candi/tmp/unpack/Trilinos-trilinos-release-14-0-0/packages/stratimikos/src/St …
=> Error about building Trilinos 14.0.0 with candi

deal.II-toolchain/packages/sundials.package
=> sundials: enable optimizations, disable examples
